OHDSI/CohortDiagnostics

- inst/sql/sql_server/IncidenceProportionYearAgeGenderStratified.sql
@schuemie - can you merge this into a new develop branch here?
> Fixes table drop - thanks @hms1

- inst/sql/sql_server/OrphanCodes.sql
> Replaces left join with not in

- R/RunDiagnostics.R
- man/runCohortDiagnostics.Rd
Addresses enhancement request here https://github.com/OHDSI/CohortDiagnostics/issues/32
> Adds ability to pass covariateSettings object to modify default table 1 specs

- R/RunDiagnostics.R
https://github.com/OHDSI/CohortDiagnostics/issues/58
This solution works when Cohort Diagnostics is resumed after interruption
> Read counts from cohort_count.csv when counts object does not exist

- inst/shiny/DiagnosticsExplorer/server.R
Fixes https://github.com/OHDSI/CohortDiagnostics/issues/51
> Missing thousands-commas

- NEWS.md
- R/RunDiagnostics.R
https://github.com/OHDSI/CohortDiagnostics/issues/72
> Adds information about run times for each step in Cohort Diagnostics

- DESCRIPTION
- inst/shiny/DiagnosticsExplorer/server.R
To comply with HADES style guide.
Hi @schuemie if you get a chance, could you please test the shiny app on your environment.
Next step  - i am going to separate out R code from server.R into standalone scripts
> Added package name and named (vs positional) arguments

- .gitignore
- R/RunDiagnostics.R
https://github.com/OHDSI/CohortDiagnostics/issues/101
> Changed the way regular expressions parses SQL

- R/Shiny.R
Fixes https://github.com/OHDSI/CohortDiagnostics/issues/104
> Ensuring data is deduplicated

- R/CohortCharacterizationDiagnostics.R
- R/CohortComparisonDiagnostics.R
- R/CohortConstruction.R
- R/CohortLevelDiagnostics.R
- R/IncidenceRates.R
- R/Private.R
- R/RunDiagnostics.R
- R/RunDiagnosticsExternalCounts.R
- R/Shiny.R
- R/TimeDistributions.R
- inst/shiny/DiagnosticsExplorer/R/Plots.R
- inst/shiny/DiagnosticsExplorer/R/Tables.R
- inst/shiny/DiagnosticsExplorer/global.R
- inst/shiny/DiagnosticsExplorer/html/temporalCharacterization.html
- inst/shiny/DiagnosticsExplorer/server.R
- inst/shiny/DiagnosticsExplorer/ui.R
- man/getCohortCharacteristics.Rd
- man/runCohortDiagnostics.Rd
Resolves https://github.com/OHDSI/CohortDiagnostics/issues/106
https://github.com/OHDSI/CohortDiagnostics/issues/87
https://github.com/OHDSI/CohortDiagnostics/issues/68
https://github.com/OHDSI/CohortDiagnostics/issues/61
https://github.com/OHDSI/CohortDiagnostics/issues/52
https://github.com/OHDSI/CohortDiagnostics/issues/26
> Temporal characterization and bug fixes

- inst/shiny/DiagnosticsExplorer/ui.R
This change stops the error found in issue-165
> Commas causing problems with Ui code in R version 3.5.1

- R/ConceptSets.R
> Fixes #174

- R/LoadDatabaseFiles.R
Note, assumes CSV files store NA as empty.
> Import to postgres

- inst/shiny/DiagnosticsExplorer/server.R
- inst/shiny/DiagnosticsExplorer/ui.R
* Added Filters to incidence rate plot
* Renamed tab from cohort description to cohort definition
> Filters for incidence rate plot, rename from cohort description to cohort definition

- .github/workflows/R_CMD_check_Hades.yml
- NEWS.md
- R/CohortCharacterizationDiagnostics.R
- inst/shiny/DiagnosticsExplorer/R/Tables.R
Two changes:
- Fixes computation of standard deviation as listed in issue #322 
- Sets error_on to "warning" for consistency with other HADES packages. (note: there are many warnings)
> Fix computation of standard deviation, and fix GitHub Action

- NEWS.md
- R/RunDiagnostics.R
- inst/settings/resultsDataModelSpecification.csv
- inst/sql/postgresql/CreateResultsDataModel.sql
Added metadata field https://github.com/OHDSI/CohortDiagnostics/issues/125
> Adding metadata field

- R/CohortConstruction.R
- R/MetaDataDiagnostics.R
- R/RunDiagnostics.R
- inst/shiny/DiagnosticsExplorer/server.R
- inst/shiny/DiagnosticsExplorer/ui.R
* Fixed bug in cohort construction in webapi mode
> Restore diagnostics explorer (#2)

- R/Shiny.R
- inst/shiny/DiagnosticsExplorer/R/Plots.R
used a fixed number of breaks and rounds output
Fixes #354
> Alteration to uncrowd xaxis when showing many years

- NEWS.md
- inst/shiny/DiagnosticsExplorer/R/Plots.R
- inst/shiny/DiagnosticsExplorer/R/Results.R
- inst/shiny/DiagnosticsExplorer/global.R
- inst/shiny/DiagnosticsExplorer/server.R
- inst/shiny/DiagnosticsExplorer/ui.R
* Implemented concept set expression json in cohort definition tab,
* Analysis name and domain name filter in characterization tab
* Analysis name filter and domain name filter in compare temporal characterization tab.
* Resolved and mapped concepts in local mode
* Update NEWS.md
* Reused drop down for compare plots
* Add limits to plot compare
* Updated temporal and cohort compare plots
> Additional changes to diagnostics explorer

- inst/shiny/DiagnosticsExplorer/server.R
- inst/shiny/DiagnosticsExplorer/ui.R
* Concept set id filters in characterization, temporal, compare char and compare temporal
* index event break down filters in single row
> Restore diagnostics explorer3 (#5)

- inst/shiny/DiagnosticsExplorer/R/Plots.R
- inst/shiny/DiagnosticsExplorer/R/Results.R
- inst/shiny/DiagnosticsExplorer/R/Tables.R
- inst/shiny/DiagnosticsExplorer/server.R
- inst/shiny/DiagnosticsExplorer/ui.R
* Compare temporal characterization plot changes
* Cohort overlap tab reorder
* Update to plotCohortComparison plot
> bug fixes - Update to plot comparing covariates

- inst/shiny/DiagnosticsExplorer/R/Plots.R
- inst/shiny/DiagnosticsExplorer/R/Tables.R
- inst/shiny/DiagnosticsExplorer/global.R
- inst/shiny/DiagnosticsExplorer/server.R
- inst/shiny/DiagnosticsExplorer/ui.R
* Orphan concept set data filtering
* restrict negative values in incidence rate plot - Y axis
* Replaced null value with zero in cohort counts
* Sorted ShortName in incident rate plot
* Sorted Cohort Short name in time distribution plot
* Compare temporal - blank plots.
* Avoiding tibble return inside renderPlot
* Index event breakdown filter changes.
* Visit context changes
* Floating point precision in cohort overlap tooltip
* Adding 0 if value is missing in visit context
* Selected database display in temporal characterization
* Compare temporal characterization column filters
* Displaying selected database in compare cohort characterization
* X and Y axis label changes in compare temporal characterization and compare characterization
* Css changes in displaying selected cohort and …
> Diagnostics explorer

- .github/workflows/R_CMD_check_Hades.yml
- extras/PackageMaintenance.R
- tests/testthat/setup.R
For a new user coming into testing of this package, it's tricky to get the environment variables right. This adds checks to see if the expected environmental variables exist, and also hard codes the cohort_diagnostics schema name as Martijn suggested in #481
> Improve checks and usage of environment variables

- R/CohortComparisonDiagnostics.R
- R/CohortConstruction.R
cherry picked from changes to master, this is aimed at develop. All PRs should merge develop after this is included
> tidyr::replace_na bug fixes

- DESCRIPTION
- NEWS.md
- R/CohortConstruction.R
- docs/404.html
- docs/articles/CreatingAStudyPackage.html
- docs/articles/DatabaseModeInDiagnosticsExplorer.html
- docs/articles/RunningCohortDiagnostics.html
- docs/articles/ViewingResultsUsingDiagnosticsExplorer.html
- docs/articles/WhatIsCohortDiagnostics.html
- docs/articles/index.html
- docs/authors.html
- docs/index.html
- docs/news/index.html
- docs/pkgdown.yml
- docs/reference/CohortDiagnostics-package.html
- docs/reference/checkInputFileEncoding.html
- docs/reference/createResultsDataModel.html
- docs/reference/executeDiagnostics.html
- docs/reference/getCohortCounts.html
- docs/reference/getResultsDataModelSpecifications.html
- docs/reference/index.html
- docs/reference/instantiateCohortSet.html
- docs/reference/launchCohortExplorer.html
- docs/reference/launchDiagnosticsExplorer.html
- docs/reference/loadCohortsFromPackage.html
- docs/reference/preMergeDiagnosticsFiles.html
- docs/reference/runCohortDiagnostics.html
- docs/reference/uploadResults.html
- inst/shiny/DiagnosticsExplorer/global.R
Issue causes inclusion stats to be blank
> Hot fix 2.2.2

- NEWS.md
- R/RunDiagnostics.R
Merge from hotfix back in to develop
> Merge master dev 2.2.2

- inst/shiny/DiagnosticsExplorer/server.R
> Fix for empty concept set expressions causing crashes

- R/CohortLevelDiagnostics.R
https://github.com/OHDSI/CohortDiagnostics/issues/740
> Remove unneeded checks

- inst/sql/sql_server/CreateResultsDataModel.sql
https://github.com/OHDSI/CohortDiagnostics/issues/765
> Change some FLOAT to BIGINT, and distribution key

- R/RunDiagnostics.R
> issue #833 - integer checks for temporalCovariateSettings

- inst/shiny/DiagnosticsExplorer/R/CohortDefinitionModule.R
- inst/shiny/DiagnosticsExplorer/R/InclusionRulesModule.R
> Fix concept set diagnostics

- inst/shiny/DiagnosticsExplorer/R/CharacterizationModule.R
- inst/shiny/DiagnosticsExplorer/R/CohortCountsModule.R
- inst/shiny/DiagnosticsExplorer/R/CompareCharacterizationModule.R
- inst/shiny/DiagnosticsExplorer/R/ConceptsInDataSourceModule.R
- inst/shiny/DiagnosticsExplorer/R/DisplayFunctions.R
- inst/shiny/DiagnosticsExplorer/R/InclusionRulesModule.R
- inst/shiny/DiagnosticsExplorer/R/IndexEventModule.R
- inst/shiny/DiagnosticsExplorer/R/OrphanConceptsModule.R
- inst/shiny/DiagnosticsExplorer/R/TemporalCharacterizationModule.R
- inst/shiny/DiagnosticsExplorer/R/TimeDistributionsModule.R
- inst/shiny/DiagnosticsExplorer/R/VisitContextModule.R
Reactable version in cran updated so downloads can now be supported.
Resolves #807
> Reactable csv download

- .gitignore
- inst/shiny/DiagnosticsExplorer/R/Annotation.R
- inst/shiny/DiagnosticsExplorer/R/InclusionRulesModule.R
- inst/shiny/DiagnosticsExplorer/R/OrphanConceptsModule.R
- inst/shiny/DiagnosticsExplorer/R/ResultRetrieval.R
- inst/shiny/DiagnosticsExplorer/R/Shared.R
- inst/shiny/DiagnosticsExplorer/R/StartUpScripts.R
- inst/shiny/DiagnosticsExplorer/tests/test-Annotation.R
Add userCredentials.csv file to gitignore
Fix bug to sql annotation_id calculation  https://github.com/OHDSI/CohortDiagnostics/issues/887
Fix warning in orphan concept module https://github.com/OHDSI/CohortDiagnostics/issues/886
> Minor bug fixes

- NEWS.md
- inst/sql/sql_server/CohortEntryBreakdown.sql
> Use group by across index event counts

- R/RunDiagnostics.R
https://github.com/OHDSI/CohortDiagnostics/issues/899
> Logger file would be written in output folder

- inst/shiny/DiagnosticsExplorer/server.R
- inst/shiny/DiagnosticsExplorer/ui.R
Only impacts shiny, will not require a new release
> Shiny hotfix Temporal char reactive fix

- R/IncidenceRates.R
> Issue 915 ir washout null

- R/ResultsDataModel.R
- tests/testthat/test-ResultsDataModel.R
> Issue 713 validate upload

- inst/shiny/DiagnosticsExplorer/R/CohortCountsModule.R
- inst/shiny/DiagnosticsExplorer/R/CohortDefinitionModule.R
- inst/shiny/DiagnosticsExplorer/R/DiagnosticsExplorerModule.R
- inst/shiny/DiagnosticsExplorer/R/DisplayFunctions.R
- inst/shiny/DiagnosticsExplorer/R/Results.R
> Issue #921 - resolved concepts not displaying correctly

- R/CohortRelationship.R
- R/RunDiagnostics.R
- man/executeDiagnostics.Rd
- man/launchDiagnosticsExplorer.Rd
- man/runCohortRelationshipDiagnostics.Rd
- tests/testthat/setup.R
- tests/testthat/test-moduleCohortRelationship.R
Broken outside of incremental mode. Fix for this and other broken unit tests bad docs etc.
> Cohort relationships fix

- NEWS.md
- R/DataSourceInformation.R
> fix for source table exists

- DESCRIPTION
- NEWS.md
- R/IncidenceRates.R
> Incidence exports as 0

- inst/shiny/DiagnosticsExplorer/server.R
- inst/shiny/DiagnosticsExplorer/ui.R
* FIx for namespace of characterization_view/cohorDiagnoisticsServer OhdsiShinyModules in shiny app causing app to crash
> Fix for loading app with new osm

- DESCRIPTION
- R/CohortCharacterizationDiagnostics.R
- R/ExportCharacterization.R
> filter covariates in FeatureExtraction

- inst/shiny/DiagnosticsExplorer/README.md
This is just a quick fix to improve the `README.md` of the Diagnostics Explorer Shiny App.
> Fix README of Diagnostics Explorer Shiny App

- inst/settings/resultsDataModelSpecification.csv
- inst/sql/sql_server/CohortRelationship.sql
- inst/sql/sql_server/CreateResultsDataModel.sql
- inst/sql/sql_server/migrations/Migration_5-v3_3_0_remove_overlap_table.sql
- inst/sql/sqlite/migrations/Migration_5-v3_3_0_remove_overlap_table.sql
Adds migrations to remove unused tables and columns
> Tidy cohort relationships

- inst/sql/sql_server/CreateResultsDataModel.sql
Proposes to add back the SQL removed per #1139
> Restore original createResultsDataModel.sql

- R/RunDiagnostics.R
> fix issue 1070

- DESCRIPTION
- R/Shiny.R
- tests/testthat/test-1-ResultsDataModel.R
> Abort when no results files are found

- CohortDiagnostics.Rproj
- NEWS.md
- R/RunDiagnostics.R
- R/Shiny.R
- inst/settings/resultsDataModelSpecification.csv
- inst/sql/sql_server/migrations/Migration_7-v3_4_0_measurement_exports.sql
- man/executeDiagnostics.Rd
- man/getDefaultCovariateSettings.Rd
Aims to resolve Issue #1147 - which has value and range pairs in characterization.
> Issue 1147 measurments
